### ISSUE TITLE
CSS error in Firefox

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/sudoku-solver#1]
The app is not the best in Firefox 85. Screenshot included.
![Screenshot_2021-02-17 Sudoku solver](https://user-images.githubusercontent.com/64044481/108267888-1523b380-716c-11eb-9449-1896918919f5.png)

**Comment by Sasszem** [comment]
Apparently `width: fit-content` does not work in FF, but we can use `width: -moz-fit-content`

**Comment by Sasszem** [comment]
Should be fixed by 46e91e2e
We'll see after I rebuild the thing

**Comment by Sasszem** [comment]
Updated the public build.
@Btimes2 Please verify that it works now and then close the issue!

**Comment by Btimes2** [comment]
Thank you, works nicely :)
