### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/sudoku-solver#4]
Could you maybe easily make it more game-like?

Like with a 
* create new game button, using possibly a sudoku creation program like py-sudoku, or a conveniently large database of pre-generated sudokus, like this one: https://www.kaggle.com/radcliffe/3-million-sudoku-puzzles-with-ratings. This database has a difficulty rating system from 0 to 8.5. I guess you could pick like 100 or 1000 random sudokus from each difficulty level, store it in json, and that would be more than enough for any players, but still a relatively small (<100 KB) database. 
* revert all button (revert to the original puzzle numbers)
* clear all button (to be able to input a whole new puzzle)
* of course, the numbers given initially could not be changed by the users in this "game" mode
* visual clue when reaching the solved state, maybe fill the cells with green, and/or  make a congratulate message (something in a popup)
* import-export feature (import from plaintext, export to plaintext). With importing plaintext, you could also test your app using the database above. By exporting, you could maybe save the sudokus which your users put in, so you can later check the ones they could not solve with your app.

With these and some CSS magic, you could even make a "commercial" sudoku site with Google Ads.

**Comment by Sasszem** [comment]
This project is named sudoku-**solver**, as my intention was to create a program that solves these puzzles.
Feel free to fork my project if you want to make a game out of it!

**Comment by Btimes2** [comment]
My original idea was simpler, I guess I got carried away :)

A demo feature and an import feature would be nice since testers have to manually input 81 cells to test the program. And exporting is rather like saving states, to be imported later - just not automatically to the browser's local storage, but manually to a text file.
